name: Update Dev and Staging branches

on:
  push:
    branches: [ main ]

jobs:
  updateBranches:
    name: Update branches
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Fetch main branches
        run: |
          git push origin :lorem
