name: Update Dev and Staging branches

on:
  push:
    branches: [ main ]

jobs:
  updateBranches:
    name: Update branches
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: staging

      - name: Update staging
        run: |
          git pull origin main
          git push origin staging


      - uses: actions/checkout@v2
        with:
          ref: dev

      - name: Update dev
        run: |
          git fetch origin main
          git checkout main
          git branch -D dev
          git checkout -b dev
          git push origin :dev
          git push origin dev