name: Update Dev and Staging branches

on:
  push:
    branches: [ main ]

jobs:
  updateBranches:
    name: Update branches
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Fetch main branches
        run: |
          git fetch origin main
          git fetch origin staging
          git fetch origin dev

      - uses: actions/checkout@v2
        with:
          ref: staging
      - name: Update staging
        run: |
          git pull -r origin main



# git config user.email "auto-update-branches-bot@github.com"
# git config user.name "Auto Update Branchs Bot"

# git pull origin staging
# git pull --rebase origin main

# echo "${{ github.ref }}"
# echo "${{ github.sha }}"
# echo "${{ github.head_ref }}"
# echo "${{ github.base_ref }}"