name: Update Dev and Staging branches

on:
  push:
    branches: [ main ]

jobs:
  updateBranches:
    name: Update branches
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Remove lorem branch
        run: |
          git push origin :lorem
        continue-on-error: true

      - name: Create lorem branch
        run: |
          git checkout -b lorem
