name: Update Dev and Staging branches

on:
  push:
    branches: [ main ]
    paths-ignore:
      - .github/workflows/main.yml

jobs:
  updateBranches:
    name: Update branches
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Fetch main branches
        run: |
          git push origin :lorem
