name: Update Dev and Staging branches

on:
  push:
    branches: [ main ]

jobs:
  updateBranches:
    name: Update branches
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Update staging
        run: |
          git fetch origin staging
          git fetch origin dev

          git checkout staging
          git pull origin main
          git push origin staging

          git checkout dev
          git pull origin main
          git push origin dev
