name: Update prod branch on release

# Controls when the action will run. 
on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  updateBranch:
    name: Update Branchs
    runs-on: ubuntu-latest

    steps:
      - name: Update staging branch
      - uses: actions/checkout@v2

        with:
          ref: staging

      - name: Update staging
        run: |
          git pull origin main
          git push origin staging
      
      - name: Update dev branch
      - uses: actions/checkout@v2

        with:
          ref: dev

      - name: Update dev
        run: |
          git pull origin main