name: Update prod branch on release

on:
  push:
    branches: [ main ]

jobs:
  updateBranches:
    name: Update Branches
    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v2
      #   with:
      #     ref: staging

      # - name: Update staging
      #   run: |
      #     git pull origin main
      #     git push origin staging

      - uses: actions/checkout@v2
        with:
          ref: dev

      - name: Update dev
        run: |
          git pull origin main
