name: Update Dev and Staging branches

on:
  push:
    branches: [ main ]

jobs:
  updateBranches:
    name: Update branches
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Fetch main branches
        run: |
          git config --global user.email "auto-update-branches-bot@github.com"
          git config --global user.name "Auto Update Branchs Bot"

          git fetch origin staging
          git checkout staging

          git rebase -X theirs origin/main
          git push origin staging -f



# git config user.email "auto-update-branches-bot@github.com" --allow-unrelated-histories
# git config user.name "Auto Update Branchs Bot"

# git pull origin staging
# git pull --rebase origin main

# echo "${{ github.ref }}"
# echo "${{ github.sha }}"
# echo "${{ github.head_ref }}"
# echo "${{ github.base_ref }}"