name: Update Dev and Staging branches

on:
  push:
    branches: [ main ]
    paths-ignore:
      - .github/workflows/main.yml

jobs:
  updateBranches:
    name: Update branches
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Fetch main branches
        run: |
          git config --global user.email "auto-update-branches-bot@github.com"
          git config --global user.name "Auto Update Branchs Bot"

          git fetch origin staging
          git checkout staging

          git pull -r -X ours origin main
          git push -f origin staging