name: Update Dev branch

on:
  push:
    branches: [ main ]
    paths-ignore:
      - .github/workflows/main.yml

jobs:
  updateBranches:
    name: Update branch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Update dev branch
        run: |
          git push origin :lorem